#include:
#- project: ladyka/gitlab-common
#  ref: ci-ui-aws-deploy
#  file: .gitlab-ci-ui-react.yml

stages:
  - build-and-deploy-prod

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node-modules
  policy: pull-push

default:
  image: node:20

build-and-deploy-prod:
  stage: build-and-deploy-prod
  before_script:
    - set -x
    - chmod 600 $SSH_KEY_FILE
    - export SERVER_SSH_CONNECTION=ubuntu@${HOST_TARGET_PROD}
    - npm install
    - npm install --location=global create-pwa
    - WWW_DIR=/poputka/www
  script:
    - npm run build ;
#    - cd out ; create-pwa --icon="./android-chrome-192x192.png" --launch="./android-chrome-512x512.png" ; cd ..
    - tar -cf bundle.tar out
    - scp -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${CI_PROJECT_DIR}/bundle.tar ${SERVER_SSH_CONNECTION}:/tmp/
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${SERVER_SSH_CONNECTION} "cd /tmp ; tar -xf bundle.tar ; rm -rf $WWW_DIR; mv out $WWW_DIR"
#    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${SERVER_SSH_CONNECTION} ""
#    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${SERVER_SSH_CONNECTION} ""
#  only:
#    - tags

