#include:
#- project: ladyka/gitlab-common
#  ref: master
#  file: .gitlab-ci-ui-next-react.yml

stages:
  - build-and-deploy-dev
  - build-and-deploy-prod

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node-modules
  policy: pull-push

default:
  image: node:20

build-and-deploy-dev:
  stage: build-and-deploy-dev
  before_script:
    - set -x
    - chmod 600 $SSH_KEY_FILE
    - export SERVER_SSH_CONNECTION=ubuntu@${HOST_TARGET_DEV}
    - npm install
  script:
    - npm run build ;
    - tar -cf bundle.tar .
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${SERVER_SSH_CONNECTION} "rm -fr $WWW_DIR ; mkdir -p $WWW_DIR"
    - scp -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${CI_PROJECT_DIR}/bundle.tar ${SERVER_SSH_CONNECTION}:$WWW_DIR
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${SERVER_SSH_CONNECTION} "cd $WWW_DIR ; tar -xf bundle.tar"
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${SERVER_SSH_CONNECTION} "sudo systemctl restart ${CI_PROJECT_NAME}.service"
  only:
    - main

build-and-deploy-prod:
  stage: build-and-deploy-prod
  before_script:
    - set -x
    - chmod 600 $SSH_KEY_FILE
    - export SERVER_SSH_CONNECTION=ubuntu@${HOST_TARGET_PROD}
    - npm install
  script:
    - npm run build ;
    - tar -cf bundle.tar .
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${SERVER_SSH_CONNECTION} "rm -fr $WWW_DIR ; mkdir -p $WWW_DIR"
    - scp -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${CI_PROJECT_DIR}/bundle.tar ${SERVER_SSH_CONNECTION}:$WWW_DIR
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${SERVER_SSH_CONNECTION} "cd $WWW_DIR ; tar -xf bundle.tar"
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY_FILE ${SERVER_SSH_CONNECTION} "sudo systemctl restart ${CI_PROJECT_NAME}.service"
  only:
    - tags
